blank_issues_enabled: false
contact_links:
  - name: Report a bug or request a feature
    url: https://github.com/syahrinseth/eloquent-filter/issues/new
    about: Report a reproducible bug or request a feature
